# Site
name: "Blog de Notas"
title: "Tecniablog"
description: "Este blog contiene mis notas de programación, Linux, DevOps y otras referencias"
logo: 'assets/images/TecniaLogo.png'
favicon: 'favicon.ico'
baseurl: /
google_analytics: "UA-101880560-2"
disqus: 'jmontoyac@gmail.com'
mailchimp-list: 
include: ["_pages", "_includes"]
permalink: /:title/

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Authors
authors:
  jay:
    name: Jay 
    display_name: Jay
    avatar: assets/images/jemc.jpeg
    #gravatar: 49510f2a2c1b780cdd29da790028e6b9
    gravatar: assets/images/jemc.jpeg
    email: jmontoyac@gmail.com
    web: https://jmontoyac.github.io/tecniablog/
    twitter: https://twitter.com/jmontoyarib
    description: "Linux, SysAdm, DevOps"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-4367921847996027"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
